% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 11-Jan-2016 21:12:02

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 80000;  % Sampling Frequency

Fstop = 24000;  % Stopband Frequency
Fpass = 26000;  % Passband Frequency
Dstop = 0.001;  % Stopband Attenuation
Dpass = 0.001;  % Passband Ripple
dens  = 16;     % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);